
name: 'dbt_core'
version: '1.0.0'

profile: 'dbt_core'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  dbt_core:
    stage:
      +schema: staging
      +materialized: view
      +tags: ["staging"]

    raw_vault:
      +schema: raw_vault
      +materialized: incremental
      +tags: ["raw_vault"]

    business_vault:
      +schema: business_vault
      +tags: ["business_vault"]

    marts:
      +schema: marts
      +tags: ["marts"]

seeds:
  dbt_core:
    +schema: staging
